//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovaya
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class marks
    {
        public int id_mark { get; set; }
        public Nullable<int> id_student { get; set; }
        public Nullable<int> id_subject { get; set; }
        public Nullable<int> mark { get; set; }
        public Nullable<int> lesson_number { get; set; }
        public Nullable<System.DateTime> lesson_date { get; set; }
        public Nullable<int> semester { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual students students { get; set; }
        public virtual subjects subjects { get; set; }
    }
}
